#!/bin/sh

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
 _                 _           
| |_ _ __ __ _ ___| |__   __ _ 
| __| `__/ _` / __|  _ \ / _` |
| |_| | | (_| \__ \ |_) | (_| |
 \__|_|  \__,_|___/_.__/ \__,_|

-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
#chown abc:abc /app
chown abc:abc /config
chown abc:abc /etc/service/oauth2_proxy -R

exit 0;
